# Generated by Django 6.0.6 on 2026-07-14 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('R', 'Resident'), ('S', 'Secretary'), ('A', 'Accountant'), ('V', 'Vice Head'), ('H', 'Head')], default='R', max_length=1)),
                ('apartment_number', models.PositiveSmallIntegerField()),
                ('can_vote', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['organization', 'role', '-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'organization'), name='unique_member_organization')],
            },
        ),
    ]
